package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallInfo;
import org.linlinjava.litemall.db.domain.LitemallInfoExample;

public interface LitemallInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int insert(LitemallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    LitemallInfo selectOneByExample(LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    LitemallInfo selectOneByExampleSelective(@Param("example") LitemallInfoExample example, @Param("selective") LitemallInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    List<LitemallInfo> selectByExampleSelective(@Param("example") LitemallInfoExample example, @Param("selective") LitemallInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    List<LitemallInfo> selectByExample(LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    LitemallInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    LitemallInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallInfo record, @Param("example") LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallInfo record, @Param("example") LitemallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallInfo record);
}