package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallHomeimg;
import org.linlinjava.litemall.db.domain.LitemallHomeimgExample;

public interface LitemallHomeimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    long countByExample(LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int insert(LitemallHomeimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int insertSelective(LitemallHomeimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    LitemallHomeimg selectOneByExample(LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    LitemallHomeimg selectOneByExampleSelective(@Param("example") LitemallHomeimgExample example, @Param("selective") LitemallHomeimg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    List<LitemallHomeimg> selectByExampleSelective(@Param("example") LitemallHomeimgExample example, @Param("selective") LitemallHomeimg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    List<LitemallHomeimg> selectByExample(LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    LitemallHomeimg selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallHomeimg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    LitemallHomeimg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallHomeimg record, @Param("example") LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallHomeimg record, @Param("example") LitemallHomeimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallHomeimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_homeimg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallHomeimg record);
}