package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSupply;
import org.linlinjava.litemall.db.domain.LitemallSupplyExample;

public interface LitemallSupplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    long countByExample(LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int insert(LitemallSupply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSupply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    LitemallSupply selectOneByExample(LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    LitemallSupply selectOneByExampleSelective(@Param("example") LitemallSupplyExample example, @Param("selective") LitemallSupply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    List<LitemallSupply> selectByExampleSelective(@Param("example") LitemallSupplyExample example, @Param("selective") LitemallSupply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    List<LitemallSupply> selectByExample(LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    LitemallSupply selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSupply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    LitemallSupply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSupply record, @Param("example") LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSupply record, @Param("example") LitemallSupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSupply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSupply record);
}